routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::view('/', 'welcome');

Auth::routes();
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.request');

Route::get('/home', 'HomeController@index')->name('home');
//*************** ROLES Y PERMISOS ********************//
Route::resource('users', 'UserController')->names('users');
Route::resource('roles', 'RoleController')->names('roles');
Route::resource('permissions', 'PermissionController')->names('permissions');

Route::resource('personas', 'PersonaController')->names('personas');

Route::resource('pilotos', 'PilotoController')->names('pilotos');
Route::post('/pilotos/getPilotos/','PilotoController@getPilotos')->name('pilotos.getPilotos');

Route::resource('paracaidistas', 'ParacaidistaController')->names('paracaidistas');
Route::post('/paracaidistas/getParacaidistas/','ParacaidistaController@getParacaidistas')->name('paracaidistas.getParacaidistas');

Route::resource('zonas', 'ZonaController')->names('zonas');

Route::resource('eventos', 'EventoController')->names('eventos');
Route::post('/eventos/getEventos/','EventoController@getEventos')->name('eventos.getEventos');

Route::resource('avionetas', 'AvionetaController')->names('avionetas');
Route::post('/avionetas/getAvionetas/','AvionetaController@getAvionetas')->name('avionetas.getAvionetas');

Route::resource('escuelas', 'EscuelaController')->names('escuelas');

Route::resource('suspensionParacaidistas', 'SuspensionParacaidistaController')->names('suspensionParacaidistas');
Route::resource('pruebas', 'TitulacionTipoController')->names('pruebas');
Route::resource('propietarios', 'PropietariosEscuelaController')->names('propietarios');
Route::resource('climaticas', 'CondicionesClimaticaController')->names('climaticas');

//************************************* DECOLAJES *****************************************//

Route::resource('decolajes', 'DecolajeController')->names('decolajes');
Route::get('decolajes/change_status/{decolaje}', 'DecolajeController@change_status')->name('change.status.decolajes');
Route::get('decolajes/pdf/{decolaje}', 'DecolajeController@pdf')->name('decolajes.pdf');

Route::get('/clima', function(){
    $location = '3439137';
    $apiKey = '9d38cd5e976eccd05e223a2ce51ef70f';

    $response = Http::get("https://api.openweathermap.org/data/2.5/weather?id={$location}&appid={$apiKey}");
    dd($response->json());

    return view('welcome', ['currentWeather' => $response->json()]);
});




// Route::resource('avionetas', 'AvionetaController')->names('avionetas');

resources/views/admin/tipoTitulacion/_form.blade.php
<div class="form-row">

    <div class="form-group col-md-4">
        <div class="form-group">
            <label for="nombre">Nombre</label>
            <div class="input-group">
                <div class="input-group-prepend">
                    <span class="input-group-text"><i class="far fa-keyboard menu-icon"></i></span>
                </div>
                <input type="text" name="nombre" id="nombre" class="form-control" placeholder="" aria-describedby="helpId" required>
            </div>
            @if ($errors->has('nombre'))
                <small class="form-text text-danger">{{ $errors->first('nombre')}}</small>
            @endif
        </div>
    </div>

    
</div>
<div class="clearfix"></div>

resources/views/admin/tipoTitulacion/create.blade.php
@extends('adminlte::page')
@section('title','Registro de Tipos')
@section('css')
@stop
@section('content_header')
@stop
@section('content')

<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Registrar Tipo de titulación</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="{{route('home')}}">Dashboard</a></li>
                    <li class="breadcrumb-item"><a href="{{route('pruebas.index')}}">Tipos de Titulaciones</a></li>
                    <li class="breadcrumb-item active" aria-current="page">Registro de Tipo</li>
                </ol>
            </div>
        </div>
    </div>
</section>

<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card card-secondary">
                    <div class="card-header">
                        <h3 class="card-title">Nuevo Tipo de Titulación</h3>
                    </div>

                    {!! Form::open(['route'=>'pruebas.store', 'method'=>'POST']) !!}
                        <div class="card-body">
                            @include('admin.tipoTitulacion._form')
                        </div>
                        <div class="card-footer">
                            <button type="submit" class="btn btn-primary mr-2">Registrar</button>
                            <a href="{{route('pruebas.index')}}" class="btn btn-light">Cancelar</a>
                        </div>
                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
</section>

@stop
@section('js')
@stop

resources/views/admin/tipoTitulacion/edit.blade.php
@extends('adminlte::page')
@section('title','Editar Tipo de titulación')
@section('css')
@stop
@section('content_header')
@stop
@section('content')
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
               <h1>Editar Tipo</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="{{route('home')}}">Dashboard</a></li>
                    <li class="breadcrumb-item"><a href="{{route('pruebas.index')}}">Tipos de Titulaciones</a></li>
                    <li class="breadcrumb-item active" aria-current="page">Editar Tipo</li>
                </ol>
            </div>
        </div>
    </div>
</section>

<!-- Main content -->
<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <!-- TITULO DEL CARD -->
                <div class="card card-secondary">
                    <div class="card-header">
                        <h3 class="card-title">Editar Tipo</h3>
                    </div>
                    {!! Form::model($titulacionTipo, ['route'=>['pruebas.update', $titulacionTipo], 'method'=>'PUT']) !!}
                        <div class="card-body">
                            <div class="form-row">

                                <div class="form-group col-md-4">
                                    <div class="form-group">
                                        <label for="nombre">Nombre</label>
                                        <div class="input-group">
                                            <div class="input-group-prepend">
                                                <span class="input-group-text"><i class="fa fa-keyboard menu-icon"></i></span>
                                            </div>
                                            <input type="text" name="nombre" id="nombre" class="form-control" placeholder="" aria-describedby="helpId" value="{{$titulacionTipo->nombre}}">
                                        </div>
                                        @if ($errors->has('nombre'))
                                            <small class="form-text text-danger">{{ $errors->first('nombre')}}</small>
                                        @endif
                                    </div>
                                </div>


                            </div>
                            <div class="clearfix"></div>
                        </div>
                        <div class="card-footer">
                            <button type="submit" class="btn btn-primary mr-2">Actualizar</button>
                            <a href="{{route('pruebas.index')}}" class="btn btn-light">Cancelar</a>
                        </div>
                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
</section>
@stop
@section('js')
@stop

resources/views/admin/tipoTitulacion/index.blade.php
@extends('adminlte::page')
@section('title', 'Tipos de titulaciones')
@section('css')
<<<<<<< HEAD
  
    <style>
        #titulaciontipos tbody td:eq(0) {
            text-align: left;
        }
        #titulaciontipos tbody td {
            text-align: center;
        }
    </style>
=======
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.2/css/bootstrap.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.25/css/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/responsive/2.2.9/css/responsive.bootstrap4.min.css">
>>>>>>> 2cef6c7a3e36b3a056dcc9d9ee615f2aa4addf96
@stop
@section('content_header')
@stop
@section('content')
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">

                <div class="col-sm-12 float-right">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="{{ route('home') }}">Dashboard</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Tipos de titulaciones</li>
                    </ol>
                </div>
            </div>
        </div>
    </section>

    <div class="card">
        <div class="card-header text-white bg-secondary" style="display: flex">
            <div class="col-sm-6">
                <h2>Listado de Tipos de titulaciones</h2>
            </div>
            <div class="col-sm-6 text-right">
                @can('titulaciontipos.create')
                    <a href="{{ route('pruebas.create') }}" class="nav-link">
                        <span class="btn btn-info">+ Registrar Tipo</span>
                    </a>
                @endcan
            </div>
        </div>
        <div class="card-body">
            <div class="card">
                <div class="card-body">
                    <table id="titulaciontipos" class="table table-hover text-nowrap">
                        <thead>
                            <tr class="table-active">
                                <th style="text-align: center;">Id</th>
                                <th style="text-align: center;">Nombre</th>
                                <th style="text-align: center;">Acciones</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($titulacionTipos as $titulacionTipo)
                                <tr>
                                    <th scope="row" style="text-align: center;">{{ $titulacionTipo->id }}</th>
                                    <td style="text-align: center;" >{{ $titulacionTipo->nombre }}</td>
                                    <td style="width: 50px">
                                        @csrf
                                        {!! Form::open(['route' => ['pruebas.destroy', $titulacionTipo], 'method' => 'DELETE', 'class' => 'formulario-eliminar']) !!}
                                        @can('titulaciontipos.edit')
                                            <a class="btn btn-warning" href="{{ route('pruebas.edit', $titulacionTipo) }}" title="Editar">
                                                <i class="far fa-edit"></i>
                                            </a>
                                        @endcan
                                        @can('titulaciontipos.destroy')
                                            <button class="btn btn-danger" type="submit" title="Eliminar">
                                                <i class="far fa-trash-alt"></i>
                                            </button>
                                        @endcan
                                        {!! Form::close() !!}
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
@stop
@section('js')
<<<<<<< HEAD

<script type="text/javascript">

    $(function () {
        $.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            }
        });
    
        var table = $('.data-table').DataTable({
            responsive:true,
            autoWidth: false,
=======
    <script src="https://code.jquery.com/jquery-3.5.1.js"></script>
    <script src="https://cdn.datatables.net/1.10.25/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.25/js/dataTables.bootstrap4.min.js"></script>
    <script src="https://cdn.datatables.net/responsive/2.2.9/js/dataTables.responsive.min.js"></script>
    <script src="https://cdn.datatables.net/responsive/2.2.9/js/responsive.bootstrap4.min.js"></script>
    <script src="https://cdn.datatables.net/responsive/2.2.9/js/responsive.bootstrap4.min.js"></script>

    <script>
        $(document).ready(function() {
            $('#titulaciontipos').DataTable({
                responsive: true,
                autoWidth: false,
>>>>>>> 2cef6c7a3e36b3a056dcc9d9ee615f2aa4addf96
                "language": {
                    "lengthMenu": "Mostrar " +
                        `<select class="custom-select custom-select-sm form-control form-control-sm">
                                            <option value="10">10</option>
                                            <option value="25">25</option>
                                            <option value="50">50</option>
                                            <option value="100">100</option>
                                            <option value="-1">All</option>
                                        </select>` +
                        " registros por página",
                    "zeroRecords": "No se encontró ningún registro.",
                    "info": "Mostrando la página  _PAGE_ de _PAGES_",
                    "infoEmpty": "No hay registro disponible.",
                    "infoFiltered": "(filtrado de _MAX_ registros totales)",
                    "search": "Buscar:",
                    "paginate": {
                        "next": "Siguiente",
                        "previous": "Anterior"
                    }
                }
            });
        });
    </script>

    {{-- Recepcion de sessions para los estados de insertar actualizar y eliminar desplegando el sweeatalert --}}
    @if (session('guardar') == 'ok')
        <script>
            Swal.fire({
                position: 'top-end',
                icon: 'success',
                title: 'El registro ha sido guardado existosamente.',
                showConfirmButton: false,
                timer: 1500
            })
        </script>
    @endif
    @if (session('actualizar') == 'ok')
        <script>
            Swal.fire({
                position: 'top-end',
                icon: 'success',
                title: 'El registro ha sido actualizado existosamente.',
                showConfirmButton: false,
                timer: 1500
            })
        </script>
    @endif
    {{-- Rececpcion de status del metodo destroy para la confirmacion del alert de eliminado --}}
    @if (session('eliminar') == 'ok')
        <script>
            Swal.fire(
                'Eliminado!',
                'El registro ha sido eliminado correctamente.',
                'success'
            )
        </script>
    @endif
    <script>
        $('.formulario-eliminar').submit(function(e) {
            e.preventDefault();

            Swal.fire({
                title: 'Estas seguro?',
                text: "¡No podrás revertir esto!",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: '¡Sí, bórralo!'
            }).then((result) => {
                if (result.isConfirmed) {

                    this.submit();
                }
            })

        });
    </script>
@stop