routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::view('/', 'welcome');

Auth::routes();
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.request');

Route::get('/home', 'HomeController@index')->name('home');
//*************** ROLES Y PERMISOS ********************//
Route::resource('users', 'UserController')->names('users');
Route::resource('roles', 'RoleController')->names('roles');
Route::resource('permissions', 'PermissionController')->names('permissions');

Route::resource('personas', 'PersonaController')->names('personas');

Route::resource('pilotos', 'PilotoController')->names('pilotos');
Route::post('/pilotos/getPilotos/','PilotoController@getPilotos')->name('pilotos.getPilotos');

Route::resource('paracaidistas', 'ParacaidistaController')->names('paracaidistas');
Route::post('/paracaidistas/getParacaidistas/','ParacaidistaController@getParacaidistas')->name('paracaidistas.getParacaidistas');

Route::resource('zonas', 'ZonaController')->names('zonas');

Route::resource('eventos', 'EventoController')->names('eventos');
Route::post('/eventos/getEventos/','EventoController@getEventos')->name('eventos.getEventos');

Route::resource('avionetas', 'AvionetaController')->names('avionetas');
Route::post('/avionetas/getAvionetas/','AvionetaController@getAvionetas')->name('avionetas.getAvionetas');

Route::resource('escuelas', 'EscuelaController')->names('escuelas');

Route::resource('suspensionParacaidistas', 'SuspensionParacaidistaController')->names('suspensionParacaidistas');
Route::resource('pruebas', 'TitulacionTipoController')->names('pruebas');
Route::resource('propietarios', 'PropietariosEscuelaController')->names('propietarios');
Route::resource('climaticas', 'CondicionesClimaticaController')->names('climaticas');

//************************************* DECOLAJES *****************************************//

Route::resource('decolajes', 'DecolajeController')->names('decolajes');
Route::get('decolajes/change_status/{decolaje}', 'DecolajeController@change_status')->name('change.status.decolajes');
Route::get('decolajes/pdf/{decolaje}', 'DecolajeController@pdf')->name('decolajes.pdf');

Route::get('/clima', function(){
    $location = '3439137';
    $apiKey = '9d38cd5e976eccd05e223a2ce51ef70f';

    $response = Http::get("https://api.openweathermap.org/data/2.5/weather?id={$location}&appid={$apiKey}");
    dd($response->json());

    return view('welcome', ['currentWeather' => $response->json()]);
});




// Route::resource('avionetas', 'AvionetaController')->names('avionetas');

resources/views/admin/suspension/_form.blade.php
<div class="form-row">

    <div class="form-group col-md-4">
        <div class="form-group">
            <label for="motivo">Motivo</label>
            <div class="input-group">
                <div class="input-group-prepend">
                    <span class="input-group-text"><i class="fa fa-keyboard menu-icon"></i></span>
                </div>
                <input type="text" name="motivo" id="motivo" class="form-control" placeholder="" aria-describedby="helpId"/>
            </div>
       
            <small class="form-text text-danger error-motivo"></small>     

        </div>
    </div>

    <div class="form-group col-md-4">
        <label for="fecha">Fecha de suspensión</label>
        <div class="input-group">
            <div class="input-group-prepend">
                <span class="input-group-text" id="basic-addon3"><i class="fa fa-calendar menu-icon"></i></span>
            </div>
            <input type="date" name="fecha" id="fecha" class="form-control"  value="<?php echo date("Y-m-d");?>" >
        </div>
        <small class="form-text text-danger error-fecha"></small>     

    </div>


    <div class="form-group col-md-4">
        <div class="form-group">
            <label for="paracaidista_id">Paracaidista</label>
            <div class="input-group">
                <div class="input-group-prepend">
                  <span class="input-group-text"><i class="fa fa-briefcase menu-icon"></i></span>
                </div>
                <select class="form-control" name="paracaidista_id" id="paracaidista_id">
                    <option value="" disabled selected>Selecccione un paracaidista</option>
                    @foreach ($paracaidistas as $paracaidista)
                    <option value="{{$paracaidista->id}}">{{$paracaidista->persona->nombre}}</option>
                    @endforeach
                </select>
            </div>
            <small class="form-text text-danger error-paracaidista-id"></small>     

        </div>
    </div>

    

    <div class="form-group col-md-4">
        <div class="form-group">
            <label for="duracion">Duración en horas</label>
            <div class="input-group">
                <div class="input-group-prepend">
                    <span class="input-group-text"><i class="fa fa-keyboard menu-icon"></i></span>
                </div>
                <input type="integer" name="duracion" id="duracion" class="form-control" placeholder=""
                    aria-describedby="helpId"/>
            </div>
            <small class="form-text text-danger error-duracion"></small>     

        </div>
    </div>



</div>
<div class="clearfix"></div>

resources/views/admin/suspension/index.blade.php
@extends('adminlte::page')
@section('title', 'Suspensiones')
@section('css')
 
<style>
    #suspensiones tbody td:eq(0) {
        text-align: left;
    }
    #suspensiones tbody td {
        text-align: center;
    }
</style>
@stop
@section('content_header')
@stop
@section('content')
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">

                <div class="col-sm-12 float-right">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="{{ route('home') }}">Dashboard</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Suspensiones</li>
                    </ol>
                </div>
            </div>
        </div>
    </section>

    <div class="card">
        <div class="card-header text-white bg-secondary" style="display: flex">
            <div class="col-sm-6">
                <h2>Listado de Suspensiones</h2>
            </div>
            <div class="col-sm-6 text-right">
                @can('suspensiones.create')
                    <a class="btn btn-primary" href="javascript:void(0)" id="crearNuevaSuspension">+ Agregar</a>
                @endcan
            </div>
        </div>
        <div class="card-body">
            <div class="card">
                <div class="card-body">
                    <table id="suspensiones" class="table table-striped table-bordered table-hover data-table" style="width:100%">
                        <thead>
                            <tr class="table-active">
                                <th style="text-align: center;">Id</th>
                                <th style="text-align: center;">Paracaidista</th>
                                <th style="text-align: center;">Motivo</th>
                                <th style="text-align: center;">Fecha</th>
                                <th style="text-align: center;">Duración</th>
                                <th style="text-align: center;">Acciones</th>
                            </tr>
                        </thead>
                    </table>
                </div>
            </div>
        </div>
    </div>

         <!-- Modal de registro y edición-->
         <div class="modal fade" id="agregar_suspension_modal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
            <div class="modal-dialog modal-lg ">
                <div class="modal-content">
                  
                    <div class="modal-header">
                        <h4 class="modal-title col-11 text-center" id="modelHeading"></h4>  {{--titulo del modal --}}
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
    
                    <form id="agregar_suspension_formulario" name="agregar_suspension_formulario">
                        <input type="hidden" name="suspension_id" id="suspension_id"> {{--id del registro oculto para la edicion --}}
                        <div class="modal-body">
                            @csrf
                            @include('admin.suspension._form')
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
                            <button type="submit" class="btn btn-primary" id="btnGuardarSuspension" value="create">Guardar</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
@stop
@section('js')

    <script type="text/javascript">
    
        $(function () {
            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                }
            });
        
            var table = $('.data-table').DataTable({
                responsive:true,
                autoWidth: false,
                    "language": {
                        processing: '<i class="fa fa-spinner fa-spin fa-3x fa-fw"></i><span class="sr-only">Cargando...</span> ',
                        "lengthMenu": "Mostrar "+
                                            `<select class="custom-select custom-select-sm form-control form-control-sm">
                                                <option value="10">10</option>
                                                <option value="25">25</option>
                                                <option value="50">50</option>
                                                <option value="100">100</option>
                                                <option value="-1">All</option>
                                            </select>` +
                                            " registros por página",
                        "zeroRecords": "No se encontró ningún registro.",
                        "info": "Mostrando la página  _PAGE_ de _PAGES_",
                        "infoEmpty": "No hay registro disponible.",
                        "infoFiltered": "(filtrado de _MAX_ registros totales)",
                        "search": "Buscar:",
                        "paginate":{
                            "next": "Siguiente",
                            "previous" : "Anterior"
                        }
                    },
                processing: true,
                serverSide: true,
                ajax: "{{ route('suspensionParacaidistas.index') }}",
                columns: [
                    {data: 'id'    , name: 'id'},
                    {data: 'paracaidista', name: 'paracaidista'},
                    {data: 'motivo', name: 'motivo'},
                    {data: 'fecha', name: 'fecha'},
                    {data: 'duracion', name: 'duracion'},
                    {data: 'action', name: 'action', orderable: false, searchable: false},
                    
                ],        
            
            });
    
            //Boton de crear nueva persona
            $('#crearNuevaSuspension').click(function () {
                $('#btnGuardarSuspension').val("create-suspension");
                $('#suspension_id').val('');
                $('#agregar_suspension_formulario').trigger("reset");
                $('#modelHeading').html("Nueva Suspensión").css( "font-weight","bold" );
                $('#agregar_suspension_modal').modal('show');
                
                $('.error-paracaidista-id').html('');
                $('.error-motivo').html('');
                $('.error-duracion').html('');
                $('.error-fecha').html('');
    
            });
    
            // Boton de editar persona
            $('body').on('click', '.editarSuspension', function () {
                var suspension_id = $(this).data('id');
                $.get("{{ route('suspensionParacaidistas.index') }}" +'/' + suspension_id +'/edit', function (data) {
                    $('#modelHeading').html("Editar suspensión").css( "font-weight","bold" );
                    $('#btnGuardarSuspension').val("edit-suspension");
                    $('#agregar_suspension_modal').modal('show');
                    
                    $('#suspension_id').val(data.id);
                    $('#paracaidista_id').val(data.paracaidista_id);
                    $('#motivo').val(data.motivo);
                    $('#duracion').val(data.duracion);
                    $('#fecha').val(data.fecha);

                    $('.error-paracaidista-id').html('');
                    $('.error-motivo').html('');
                    $('.error-duracion').html('');
                    $('.error-fecha').html('');
    
                })
            });
    
            //Boton de guardar persona
            $('#btnGuardarSuspension').click(function (e) {
                e.preventDefault();
                $(this).html('Guardar');
    
                $.ajax({
                    data: $('#agregar_suspension_formulario').serialize(),
                    url: "{{ route('suspensionParacaidistas.store') }}",
                    type: "POST",
                    dataType: 'json',
                    success: function (data) {
                        $('#agregar_suspension_formulario').trigger("reset");
                        $('#agregar_suspension_modal').modal('hide');
    
                        var operacion = $('#btnGuardarSuspension').val();
    
                        if( operacion == 'edit-suspension'){
                            Swal.fire({
                                position: 'top-end',
                                icon: 'success',
                                title: 'La suspensión ha sido actualizado correctamente',
                                showConfirmButton: false,
                                timer: 1500,
                            });
                        }else{
                            Swal.fire({
                            position: 'top-end',
                            icon: 'success',
                            title: data.success,
                            showConfirmButton: false,
                            timer: 1500,
                        });
    
                        }
                        table.draw();
                    },
                    
                    error: function (data) {
                        console.log('Error:', data);
                        console.log('MENSAJE', data.responseJSON.errors);
                        if(data.responseJSON.errors.paracaidista_id != null)
                        {
                            $('.error-paracaidista-id').html(data.responseJSON.errors.paracaidista_id[0]);
                        }
                        if(data.responseJSON.errors.motivo != null)
                        {
                            $('.error-motivo').html(data.responseJSON.errors.motivo[0]);
                        }
                        if(data.responseJSON.errors.duracion != null)
                        {
                            $('.error-duracion').html(data.responseJSON.errors.duracion[0]);
                        }
                        if(data.responseJSON.errors.fecha != null)
                        {
                            $('.error-fecha').html(data.responseJSON.errors.fecha[0]);
                        }
    
                    }
                });
            });
    
            $('body').on('click', '.eliminarSuspension', function () {
                var suspension_id = $(this).data("id");
                Swal.fire({
                        title: 'Estas seguro?',
                        text: "¡No podrás revertir esta operación!",
                        icon: 'warning',
                        showCancelButton: true,
                        confirmButtonColor: '#3085d6',
                        cancelButtonColor: '#d33',
                        cancelButtonText: 'Cancelar',
                        confirmButtonText: '¡Sí, continuar!'
                    }).then((result) => {
                        if (result.isConfirmed) {
                            $.ajax({
                                type: "DELETE",
                                url: "{{ route('suspensionParacaidistas.store') }}"+'/'+suspension_id,
                                success: function (data) {
                                    Swal.fire({
                                        position: 'top-end',
                                        icon: 'success',
                                        title: data.success,
                                        showConfirmButton: false,
                                        timer: 1500,
                                    }
    
                                    );
                                    table.draw();
                                },
                                error: function (data) {
                                    console.log('Error:', data);
                                }
                            });
    
    
                        }
                    });
    
                });
    
            });
            
    </script>
@stop