routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::view('/', 'welcome');

Auth::routes();
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.request');

Route::get('/home', 'HomeController@index')->name('home');
//*************** ROLES Y PERMISOS ********************//
Route::resource('users', 'UserController')->names('users');
Route::resource('roles', 'RoleController')->names('roles');
Route::resource('permissions', 'PermissionController')->names('permissions');

Route::resource('personas', 'PersonaController')->names('personas');

Route::resource('pilotos', 'PilotoController')->names('pilotos');
Route::post('/pilotos/getPilotos/','PilotoController@getPilotos')->name('pilotos.getPilotos');

Route::resource('paracaidistas', 'ParacaidistaController')->names('paracaidistas');
Route::post('/paracaidistas/getParacaidistas/','ParacaidistaController@getParacaidistas')->name('paracaidistas.getParacaidistas');

Route::resource('zonas', 'ZonaController')->names('zonas');

Route::resource('eventos', 'EventoController')->names('eventos');
Route::post('/eventos/getEventos/','EventoController@getEventos')->name('eventos.getEventos');

Route::resource('avionetas', 'AvionetaController')->names('avionetas');
Route::post('/avionetas/getAvionetas/','AvionetaController@getAvionetas')->name('avionetas.getAvionetas');

Route::resource('escuelas', 'EscuelaController')->names('escuelas');

Route::resource('suspensionParacaidistas', 'SuspensionParacaidistaController')->names('suspensionParacaidistas');
Route::resource('pruebas', 'TitulacionTipoController')->names('pruebas');
Route::resource('propietarios', 'PropietariosEscuelaController')->names('propietarios');
Route::resource('climaticas', 'CondicionesClimaticaController')->names('climaticas');

//************************************* DECOLAJES *****************************************//

Route::resource('decolajes', 'DecolajeController')->names('decolajes');
Route::get('decolajes/change_status/{decolaje}', 'DecolajeController@change_status')->name('change.status.decolajes');
Route::get('decolajes/pdf/{decolaje}', 'DecolajeController@pdf')->name('decolajes.pdf');

Route::get('/clima', function(){
    $location = '3439137';
    $apiKey = '9d38cd5e976eccd05e223a2ce51ef70f';

    $response = Http::get("https://api.openweathermap.org/data/2.5/weather?id={$location}&appid={$apiKey}");
    dd($response->json());

    return view('welcome', ['currentWeather' => $response->json()]);
});




// Route::resource('avionetas', 'AvionetaController')->names('avionetas');

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Illuminate\Support\Facades\Auth;
use Spatie\Permission\Contracts\Role;
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable
{
    use Notifiable;
    use HasRoles;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password','imagen'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function adminlte_image(){
        // return 'https://picsum.photos/300/300';
        return asset('imagen/usuarios/'.Auth::user()->imagen);
    }

    public function adminlte_desc(){
        return "Administrador";
    }
    public function adminlte_profile_url(){
        return 'users.index';
        //return 'profile/username';

    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\User;
use Illuminate\Http\Request;
use Spatie\Permission\Models\Role;
use Illuminate\Support\Facades\Hash;

use App\Http\Requests\User\StoreRequest;
use App\Http\Requests\User\UpdateRequest;
use Illuminate\Validation\Rule;
use Illuminate\Support\Facades\Validator;


class UserController extends Controller
{
    public function __construct()
    {
         $this->middleware('can:usuarios.index')->only('index');
         $this->middleware('can:usuarios.create')->only('create','store');
         $this->middleware('can:usuarios.edit')->only('edit','update');
         $this->middleware('can:usuarios.destroy')->only('destroy');
    }

    public function index()
    {
        $users = User::get();
        return view('admin.user.index',compact('users'));
    }


    public function create()
    {
        $roles =  Role::get();
        return view('admin.user.create',compact('roles'));
    }


    public function store(StoreRequest $request)
    {
        if($request->hasFile('foto')){
            $file = $request->file('foto');
            $image_name = time().'_'.$file->getClientOriginalName();
            $file->move(public_path("/imagen/usuarios"),$image_name);
        }

        $user = User::create($request->all()+[
             'imagen' =>  $image_name,
         ]);
        $user->update(['password'=> Hash::make($request->password)]);
        $user->roles()->sync($request->get('roles'));
        return redirect()->route('users.index')->with('guardar','ok');
    }


    public function show(User $user)
    {
        return view('admin.user.show',compact('user'));

    }


    public function edit(User $user)
    {
        $roles =  Role::all();
        return view('admin.user.edit',compact('user','roles'));
    }


    public function update(Request $request, User $user)
    {

        Validator::make($request->all(), [
            'email' => [
                'required',
                    Rule::unique('users')->ignore($user->id),
            ],
        ]);


        if($request->hasFile('picture')){
            $file = $request->file('picture');
            $image_name = time().'_'.$file->getClientOriginalName();
            $file->move(public_path("/imagen/usuarios"),$image_name);
        }
        //if ($user->id == 1) {

           //return redirect()->route('users.index');
        //}else{

            // $user->update($request->all());
            // $user->roles()->sync($request->get('roles'));
            // return redirect()->route('users.index');
            $user->update($request->all()+[
                'imagen' =>  $image_name,
            ]);

            $user->roles()->sync($request->roles);

            return redirect()->route('users.edit',$user)->with('info','Se asignaron los roles correctamente.');
        //}
    }



    public function destroy(User $user)
    {
         // $user->delete();
        // return back();
        if ($user->id == 1) {
            return back();
        } else {
            $user->delete();
            return back()->with('eliminar','ok');
        }
    }
}

resources/views/admin/user/_form.blade.php
<h3>Listado de roles</h3>
<div class="form-group">
 <ul class="list-unstyled">
     @foreach ($roles as $role)
        <li>
            <label>
                {!! Form::checkbox('roles[]', $role->id, null, ['class' => 'mr-1']) !!}
                {{$role->name}}
                {{-- <em>({{$role->description}})</em> --}}
            </label>
        </li>
     @endforeach
 </ul>
</div>
<div class="clearfix"></div>

resources/views/admin/user/create.blade.php
@extends('adminlte::page')
@section('title','Registro de Usuario')
@section('css')
@stop
@section('content_header')
@stop
@section('content')
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Registrar Usuario</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="{{route('home')}}">Dashboard</a></li>
                    <li class="breadcrumb-item"><a href="#">Configuración</a></li>
                    <li class="breadcrumb-item"><a href="{{route('users.index')}}">Usuarios</a></li>
                    <li class="breadcrumb-item active" aria-current="page">Registrar Usuarios</li>
                </ol>
            </div>
        </div>
        <div class="row mb-2">
            <div class="col-sm-12">
                @if ($errors->any())
                    <x-adminlte-alert class="text-uppercase" theme="danger" title="Atención!!" dismissable>
                        <ul>
                            @foreach ( $errors->all() as $error )
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </x-adminlte-alert>
                @endif
            </div>

        </div>
    </div>
</section>

<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card card-secondary">
                    <div class="card-header">
                        <h3 class="card-title">Nuevo Usuario</h3>
                    </div>

                    {!! Form::open(['route'=>'users.store', 'method'=>'POST', 'enctype'=>"multipart/form-data"]) !!}
                        <div class="card-body">
                            <div class="form-row">
                                <div class="form-group col-md-4">
                                    <div class="form-group">
                                        <label for="name">Nombre</label>
                                        <div class="input-group">
                                            <div class="input-group-prepend">
                                                <span class="input-group-text"><i class="fas fa-user menu-icon"></i></span>
                                            </div>
                                            <input type="text" name="name" id="name"  class="form-control" placeholder="" aria-describedby="helpId">
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group col-md-4">
                                    <div class="form-group">
                                        <label for="email">Correo electrónico</label>
                                        <div class="input-group">
                                            <div class="input-group-prepend">
                                                <span class="input-group-text"><i class="fas fa fa-address-book menu-icon"></i></span>
                                            </div>
                                            <input type="email" name="email" id="email"  class="form-control" placeholder="" aria-describedby="helpId">
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group col-md-4">
                                    <div class="form-group">
                                        <label for="password">Contraseña</label>
                                        <div class="input-group">
                                            <div class="input-group-prepend">
                                                <span class="input-group-text"><i class="fas fa-eye-slash menu-icon"></i></span>
                                            </div>
                                            <input type="password" name="password" id="password"  class="form-control" placeholder="" aria-describedby="helpId">
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group col-md-6">
                                    <div class="form-group">
                                        <div class="card-body">
                                            <label for="foto">Imágen del usuario</label>
                                            <div class="input-group">
                                                <input type="file" class="form-control" name="foto" id="foto" />
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="clearfix"></div>
                            @include('admin.user._form')
                        </div>
                        <div class="card-footer text-muted">
                            <button type="submit" class="btn btn-primary mr-2">Registrar</button>
                            <a href="{{route('users.index')}}" class="btn btn-light">Cancelar</a>
                        </div>
                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
</section>
@stop
@section('js')
@stop

resources/views/admin/user/edit.blade.php
@extends('adminlte::page')
@section('title','Editar de Usuario')
@section('css')
@stop
@section('content_header')
@stop
@section('content')
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
               <h1>Editar usuario: <i>{{$user->name}}</i></h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="{{route('home')}}">Dashboard</a></li>
                    <li class="breadcrumb-item"><a href="#">Archivos</a></li>
                    <li class="breadcrumb-item"><a href="{{route('users.index')}}">Usuarios</a></li>
                    <li class="breadcrumb-item active" aria-current="page">Editar Usuario</li>
                </ol>
            </div>
        </div>
        <div class="row mb-2">
            <div class="col-sm-12">
                @if ($errors->any())
                    <x-adminlte-alert class="text-uppercase" theme="danger" title="Atención!!" dismissable>
                        <ul>
                            @foreach ( $errors->all() as $error )
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </x-adminlte-alert>
                @endif
            </div>
        </div>
    </div>
</section>

@if (session('info'))
    <div class="alert alert-success">
        <strong>{{ session('info') }}</strong>
    </div>

@endif

<!-- Main content -->
<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <!-- TITULO DEL CARD -->
                <div class="card card-secondary">
                    <div class="card-header">
                        <h3 class="card-title">Editar Usuario</h3>
                    </div>
                    {!! Form::model($user, ['route'=>['users.update',$user], 'method'=>'PUT', 'enctype'=>"multipart/form-data"]) !!}
                        <div class="card-body">
                            <div class="form-row">
                                <div class="form-group col-md-4">
                                    <div class="form-group">
                                        <label for="name">Nombre</label>
                                        <div class="input-group">
                                            <div class="input-group-prepend">
                                                <span class="input-group-text"><i class="fas fa-user menu-icon"></i></span>
                                            </div>
                                            <input type="text" name="name" id="name" value="{{$user->name}}" class="form-control" placeholder="" aria-describedby="helpId">
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group col-md-4">
                                    <div class="form-group">
                                        <label for="email">Correo electrónico</label>
                                        <div class="input-group">
                                            <div class="input-group-prepend">
                                                <span class="input-group-text"><i class="fas fa fa-address-book menu-icon"></i></span>
                                            </div>
                                            <input type="email" name="email" id="email" value="{{$user->email}}" class="form-control" placeholder="" aria-describedby="helpId">
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="card-body">
                                <h4 class="card-title d-flex">Imágen del usuario</h4>
                                <input type="file" name="picture" id="picture"/>
                            </div>
                            @include('admin.user._form')

                            <div class="clearfix"></div>
                        </div>
                        <div class="card-footer text-muted">
                            <button type="submit" class="btn btn-primary mr-2">Actualizar</button>
                            <a href="{{route('users.index')}}" class="btn btn-light">Cancelar</a>
                        </div>
                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
</section>
@stop
@section('js')
@if (session('info') == 'ok')
<script>
    Swal.fire({
            position: 'top-end',
            icon: 'success',
            title: 'El registro ha sido guardado existosamente.',
            showConfirmButton: false,
            timer: 1500
            })
</script>
@endif


@stop

resources/views/admin/user/index.blade.php
@extends('adminlte::page')
@section('title','Gestión de usuarios del sistema')
@section('css')
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.2/css/bootstrap.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.25/css/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/responsive/2.2.9/css/responsive.bootstrap4.min.css">
@stop
@section('content_header')
@stop
@section('content')

<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">

            <div class="col-sm-12 float-right">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="{{route('home')}}">Dashboard</a></li>
                    <li class="breadcrumb-item"><a href="#">Configuración</a></li>
                    <li class="breadcrumb-item active" aria-current="page">Usuarios</li>
                </ol>
            </div>
        </div>
    </div>
</section>

<div class="card">
    <div class="card-header text-white bg-secondary" style="display: flex">
        <div class="col-sm-6">
            <h2>Listado de Usuarios</h2>
        </div>
        <div class="col-sm-6 text-right">
                                        @can('usuarios.create')

            <a href="{{route('users.create')}}" class="nav-link">
                <span class="btn btn-info">+ Crear nuevo Usuario</span>
            </a>
                                                    @endcan

        </div>
    </div>
    <div class="card-body">
        <div class="card">
            <div class="card-body">
                <table id="bancos" class="table table-hover text-nowrap">
                            <thead>
                                <tr>
                                    <th>Id</th>
                                    <th>Imágen</th>
                                    <th>Nombre</th>
                                    <th>Correo electrónico</th>
                                    <th>Acciones</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($users as $user)
                                <tr>
                                    <th scope="row">{{$user->id}}</th>
                                    <td><img class="img-thumbnail img-fluid" src="{{ asset('/imagen/usuarios') . '/' . $user->imagen }}" width="150" height="150"  alt=""></td>
                                    <td>{{$user->name}}
                                    </td>
                                    <td>{{$user->email}}</td>
                                    <td style="width: 50px;">
                                        {!! Form::open(['route'=>['users.destroy',$user], 'method'=>'DELETE', 'class' => 'formulario-eliminar']) !!}
                                        @can('usuarios.edit')

                                        <a class="btn btn-warning" href="{{route('users.edit', $user)}}" title="Editar">
                                            <i class="far fa-edit"></i>
                                        </a>
                                        @endcan
                                        @can('usuarios.destroy')

                                        <button class="btn btn-danger" type="submit" title="Eliminar">
                                            <i class="far fa-trash-alt"></i>
                                        </button>
                                        @endcan

                                        {!! Form::close() !!}
                                    </td>
                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
@stop
@section('js')
<script src="https://code.jquery.com/jquery-3.5.1.js"></script>
<script src="https://cdn.datatables.net/1.10.25/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.25/js/dataTables.bootstrap4.min.js"></script>
<script src="https://cdn.datatables.net/responsive/2.2.9/js/dataTables.responsive.min.js"></script>
<script src="https://cdn.datatables.net/responsive/2.2.9/js/responsive.bootstrap4.min.js"></script>
<script src="https://cdn.datatables.net/responsive/2.2.9/js/responsive.bootstrap4.min.js"></script>

<script>
    $(document).ready(function(){
        $('#bancos').DataTable({
            responsive:true,
            autoWidth: false,
            "language": {
                "lengthMenu": "Mostrar "+
                                    `<select class="custom-select custom-select-sm form-control form-control-sm">
                                        <option value="10">10</option>
                                        <option value="25">25</option>
                                        <option value="50">50</option>
                                        <option value="100">100</option>
                                        <option value="-1">All</option>
                                    </select>` +
                                    " registros por página",
                "zeroRecords": "No se encontró ningún registro.",
                "info": "Mostrando la página  _PAGE_ de _PAGES_",
                "infoEmpty": "No hay registro disponible.",
                "infoFiltered": "(filtrado de _MAX_ registros totales)",
                "search": "Buscar:",
                "paginate":{
                    "next": "Siguiente",
                    "previous" : "Anterior"
                }
            }
        });
    });
</script>

{{-- Recepcion de sessions para los estados de insertar actualizar y eliminar desplegando el sweeatalert --}}
@if (session('guardar') == 'ok')
<script>
    Swal.fire({
            position: 'top-end',
            icon: 'success',
            title: 'El registro ha sido guardado existosamente.',
            showConfirmButton: false,
            timer: 1500
            })
</script>
@endif
@if (session('actualizar') == 'ok')
<script>
    Swal.fire({
            position: 'top-end',
            icon: 'success',
            title: 'El registro ha sido actualizado existosamente.',
            showConfirmButton: false,
            timer: 1500
            })
</script>
@endif
{{-- Rececpcion de status del metodo destroy para la confirmacion del alert de eliminado --}}
@if (session('eliminar') == 'ok')
    <script>
        Swal.fire(
                'Eliminado!',
                'El registro ha sido eliminado correctamente.',
                'success'
        )
    </script>
@endif
<script>
     $('.formulario-eliminar').submit(function(e){
        e.preventDefault();

       Swal.fire({
        title: 'Estas seguro?',
        text: "¡No podrás revertir esto!",
        icon: 'warning',
        showCancelButton: true,
        confirmButtonColor: '#3085d6',
        cancelButtonColor: '#d33',
        confirmButtonText: '¡Sí, bórralo!'
        }).then((result) => {
        if (result.isConfirmed) {

            this.submit();
        }
        })

     });
</script>
@stop